name: kubernetes

on:
  workflow_call:

jobs:
  K8s:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - id: "get-credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "alura-cluster"
          location: "us-central1"

      - run: kubectl get svc

      - run: kubectl delete secret dbhost --ignore-not-found
      - run: kubectl create secret generic dbhost --from-literal=DBHOST=${{secrets.DBHOST}}

      - run: kubectl delete secret dbport --ignore-not-found
      - run: kubectl create secret generic dbport --from-literal=DBPORT=${{secrets.DBPORT}}

      - run: kubectl delete secret dbuser --ignore-not-found
      - run: kubectl create secret generic dbuser --from-literal=DBUSER=${{secrets.DBUSER}}

      - run: kubectl delete secret dbpassword --ignore-not-found
      - run: kubectl create secret generic dbpassword --from-literal=DBPASSWORD=${{secrets.DBPASSWORD}}

      - run: kubectl delete secret dbname --ignore-not-found
      - run: kubectl create secret generic dbname --from-literal=DBNAME=${{secrets.DBNAME}}

      - run: kubectl delete secret port --ignore-not-found
      - run: kubectl create secret generic port --from-literal=PORT=8000

      - run: kubectl apply -f infra-k8s/go.yaml

      - run: kubectl set image deployment/go-api go=vmoraes26/go_ci:${{github.run_number}}
